export { FacebookIcon } from "./FacebookIcon"
export { InstagramIcon } from "./InstagramIcon"
export { WhatsAppIcon } from "./WhatsAppIcon"
export { TikTokIcon } from "./TikTokIcon"
export { LinkedInIcon } from "./LinkedInIcon"
export { GitHubIcon } from "./GitHubIcon"
